export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_USER_ALL_POSTS = 'GET_USER_ALL_POSTS';
export const GET_USER_ALL_POSTS_SUCCESS = 'GET_USER_ALL_POSTS_SUCCESS';
export const GET_USER_ALL_POSTS_ERROR = 'GET_USER_ALL_POSTS_ERROR';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const GET_POST_ALL_COMMENTS = 'GET_POST_ALL_COMMENTS';
export const GET_POST_ALL_COMMENTS_SUCCESS = 'GET_POST_ALL_COMMENTS_SUCCESS';
export const GET_POST_ALL_COMMENTS_ERROR = 'GET_POST_ALL_COMMENTS_ERROR';
